server:
  port: 8078

spring:
  application:
    name: gateway
  redis:
    host: 8.130.92.141
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
#          uri: lb://userservice
          uri: http://localhost:8081/
          predicates:
            - name: Path
              args:
                pattern: /user/**
          filters:
            - StripPrefix=1
        - id: bicycle-service
#          uri: lb://bicycleservice
          uri: http://localhost:8082/
          predicates:
            - name: Path
              args:
                pattern: /bicycle/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"